# frozen_string_literal: true

require "bundler/gem_tasks"
require "rake/testtask"

# Tarea general para ejecutar todas las pruebas
Rake::TestTask.new(:test) do |t|
  t.libs << "test"
  t.libs << "lib"
  t.test_files = FileList["test/**/*_test.rb"]
end

# Tareas específicas para ejecutar solo pruebas de Hora, Fecha, Set o Triaje
Rake::TestTask.new(:hora) do |t|
  t.libs << "test"
  t.test_files = FileList["test/hora_test.rb"]
end

Rake::TestTask.new(:fecha) do |t|
  t.libs << "test"
  t.test_files = FileList["test/fecha_test.rb"]
end

Rake::TestTask.new(:set) do |t|
  t.libs << "test"
  t.test_files = FileList["test/set_test.rb"]
end

Rake::TestTask.new(:triaje) do |t|
  t.libs << "test"
  t.test_files = FileList["test/triaje_test.rb"]
end

Rake::TestTask.new(:persona) do |t|
  t.libs << "test"
  t.test_files = FileList["test/persona_test.rb"]
end

Rake::TestTask.new(:paciente) do |t|
  t.libs << "test"
  t.test_files = FileList["test/paciente_test.rb"]
end

Rake::TestTask.new(:medico) do |t|
  t.libs << "test"
  t.test_files = FileList["test/medico_test.rb"]
end

Rake::TestTask.new(:titular) do |t|
  t.libs << "test"
  t.test_files = FileList["test/titular_test.rb"]
end

task default: :test
